/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import BUS.IKhachHangService;
import BUS.KhachHangService;
import Models.KhachHang;
import Utilities.DialogHelper;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class FMGKhachHang extends javax.swing.JPanel {
    DefaultTableModel modelKhachHang;
    IKhachHangService iKhachHangService;
    /**
     * Creates new form KhachHangJpanel
     */
    public FMGKhachHang() {
        initComponents();
         modelKhachHang = (DefaultTableModel) tblKhachHang_KhachHang.getModel();
        iKhachHangService = new KhachHangService();
        fillDataTableKhachHang();
    }
    public KhachHang getFormKhachHang() {
        KhachHang KH = new KhachHang();
        try {
            KH.setTenKhachHang(txtTenKhachHang_KhachHang.getText());
            KH.setDiaChi(txtDiaChi_KhachHang.getText());
            KH.setSoDienThoai(Integer.valueOf(txtSDT_KhachHang.getText()));
            KH.setGhiChu(txtGhiChu_KhachHang.getText());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return KH;
    }
    public KhachHang setFormKhachHang() {
        KhachHang KH = new KhachHang();
        try {
            KH.setID_KhachHang(Integer.valueOf(txtMaKhachHang_KhachHang.getText()));
            KH.setTenKhachHang(txtTenKhachHang_KhachHang.getText());
            KH.setDiaChi(txtDiaChi_KhachHang.getText());
            KH.setSoDienThoai(Integer.valueOf(txtSDT_KhachHang.getText()));
            KH.setGhiChu(txtGhiChu_KhachHang.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
        return KH;
    }
    public void fillDataTableKhachHang() {
        modelKhachHang.setRowCount(0); 
        if (iKhachHangService.getData().isEmpty()) {
            return ;
        }
        for (KhachHang KH : iKhachHangService.getData()) {
            Object[] rowData = {KH.getID_KhachHang(), 
                                KH.getTenKhachHang(),KH.getDiaChi(),
                                KH.getSoDienThoai(),
                                KH.getGhiChu()
                                };
            
            modelKhachHang.addRow(rowData);
        }
    }
    public boolean validateForm() {
        if (txtTenKhachHang_KhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên khách hàng.");
            return false;
        } else if (txtDiaChi_KhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ.");
            return false;
        } else if (txtSDT_KhachHang.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 chữ số.");
            return false;
        }
        return true;
    }

    private void findDataToSQL(KhachHang view) {
        Object[] rowData = new Object[11];
        rowData[0] = view.getID_KhachHang();
        rowData[1] = view.getTenKhachHang();
        rowData[2] = view.getDiaChi();
        rowData[3] = view.getSoDienThoai();
        rowData[4] = view.getTrangThai();
        modelKhachHang.addRow(rowData);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKhachHang = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        tblKhachHang_KhachHang = new javax.swing.JTable();
        jLabel56 = new javax.swing.JLabel();
        lblLoiMaKhachHang_KhachHang5 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        txtGhiChu_KhachHang = new javax.swing.JTextPane();
        txtDiaChi_KhachHang = new javax.swing.JTextField();
        lblDiaChi_KhachHang = new javax.swing.JLabel();
        lblSDT_KhachHang = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        lblTenKhachHang_KhachHang = new javax.swing.JLabel();
        lblMaKhachHang_KhachHang = new javax.swing.JLabel();
        txtMaKhachHang_KhachHang = new javax.swing.JTextField();
        txtTenKhachHang_KhachHang = new javax.swing.JTextField();
        txtSDT_KhachHang = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ckbTimKiem_KhachHang = new javax.swing.JCheckBox();
        txtTimKiem_KhachHang = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        btnThem_KhachHang1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnThem_KhachHang = new javax.swing.JButton();
        btnSua_KhachHang = new javax.swing.JButton();
        btnXoa_KhachHang = new javax.swing.JButton();
        btnReset_KhachHang = new javax.swing.JButton();

        pnKhachHang.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnKhachHangComponentShown(evt);
            }
        });

        tblKhachHang_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Địa chỉ", "SDT", "GhiChu", "Trạng Thái"
            }
        ));
        tblKhachHang_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHang_KhachHangMouseClicked(evt);
            }
        });
        jScrollPane24.setViewportView(tblKhachHang_KhachHang);

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Khách Hàng");

        lblLoiMaKhachHang_KhachHang5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblLoiMaKhachHang_KhachHang5.setForeground(new java.awt.Color(255, 0, 51));

        txtGhiChu_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jScrollPane25.setViewportView(txtGhiChu_KhachHang);

        txtDiaChi_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtDiaChi_KhachHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaChi_KhachHangFocusLost(evt);
            }
        });

        lblDiaChi_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDiaChi_KhachHang.setText("Địa Chỉ");

        lblSDT_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSDT_KhachHang.setText("SDT");

        jLabel85.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel85.setText("Ghi Chú");

        lblTenKhachHang_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTenKhachHang_KhachHang.setText("Tên KH");

        lblMaKhachHang_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblMaKhachHang_KhachHang.setText("Mã KH");

        txtMaKhachHang_KhachHang.setEditable(false);

        txtTenKhachHang_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTenKhachHang_KhachHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenKhachHang_KhachHangFocusLost(evt);
            }
        });
        txtTenKhachHang_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHang_KhachHangActionPerformed(evt);
            }
        });
        txtTenKhachHang_KhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenKhachHang_KhachHangKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTenKhachHang_KhachHangKeyTyped(evt);
            }
        });

        txtSDT_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtSDT_KhachHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDT_KhachHangFocusLost(evt);
            }
        });

        ckbTimKiem_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ckbTimKiem_KhachHang.setText("Tìm Kiếm");
        ckbTimKiem_KhachHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbTimKiem_KhachHangItemStateChanged(evt);
            }
        });

        txtTimKiem_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTimKiem_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiem_KhachHangActionPerformed(evt);
            }
        });
        txtTimKiem_KhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiem_KhachHangKeyReleased(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel88.setText("Tên");

        btnThem_KhachHang1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnThem_KhachHang1.setText("Thêm");
        btnThem_KhachHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_KhachHang1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbTimKiem_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem_KhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbTimKiem_KhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtTimKiem_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem_KhachHang1)
                .addGap(17, 17, 17))
        );

        btnThem_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnThem_KhachHang.setText("Thêm");
        btnThem_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_KhachHangActionPerformed(evt);
            }
        });

        btnSua_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSua_KhachHang.setText("Sửa");
        btnSua_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_KhachHangActionPerformed(evt);
            }
        });

        btnXoa_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnXoa_KhachHang.setText("Xóa");
        btnXoa_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_KhachHangActionPerformed(evt);
            }
        });

        btnReset_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnReset_KhachHang.setText("Reset");
        btnReset_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset_KhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXoa_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem_KhachHang)
                .addGap(27, 27, 27)
                .addComponent(btnSua_KhachHang)
                .addGap(27, 27, 27)
                .addComponent(btnXoa_KhachHang)
                .addGap(18, 18, 18)
                .addComponent(btnReset_KhachHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnKhachHangLayout = new javax.swing.GroupLayout(pnKhachHang);
        pnKhachHang.setLayout(pnKhachHangLayout);
        pnKhachHangLayout.setHorizontalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(lblLoiMaKhachHang_KhachHang5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGap(910, 910, 910)
                        .addComponent(jLabel31))
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenKhachHang_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiaChi_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSDT_KhachHang))
                                .addGap(18, 18, 18)
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenKhachHang_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(txtDiaChi_KhachHang)
                                    .addComponent(txtSDT_KhachHang))
                                .addGap(44, 44, 44)
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel85)
                                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                .addComponent(lblMaKhachHang_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaKhachHang_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        pnKhachHangLayout.setVerticalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaKhachHang_KhachHang)
                                    .addComponent(txtMaKhachHang_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel85)))
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDiaChi_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiaChi_KhachHang)))
                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenKhachHang_KhachHang)
                                    .addComponent(txtTenKhachHang_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSDT_KhachHang)
                            .addComponent(txtSDT_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblLoiMaKhachHang_KhachHang5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhachHang_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHang_KhachHangMouseClicked
        int viTriDongVuaBam = tblKhachHang_KhachHang.getSelectedRow();
        txtMaKhachHang_KhachHang.setText(tblKhachHang_KhachHang.getValueAt(viTriDongVuaBam, 0).toString());
        txtTenKhachHang_KhachHang.setText(tblKhachHang_KhachHang.getValueAt(viTriDongVuaBam, 1).toString());
        txtDiaChi_KhachHang.setText(tblKhachHang_KhachHang.getValueAt(viTriDongVuaBam, 2).toString());
        txtSDT_KhachHang.setText(tblKhachHang_KhachHang.getValueAt(viTriDongVuaBam, 3).toString());
        txtGhiChu_KhachHang.setText(tblKhachHang_KhachHang.getValueAt(viTriDongVuaBam, 4).toString());
        //        txtTrangThai_KhachHang.setText(tblKhachHang_KhachHang.getValueAt(viTriDongVuaBam, 5).toString());
    }//GEN-LAST:event_tblKhachHang_KhachHangMouseClicked

    private void ckbTimKiem_KhachHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbTimKiem_KhachHangItemStateChanged

    }//GEN-LAST:event_ckbTimKiem_KhachHangItemStateChanged

    private void txtTimKiem_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiem_KhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiem_KhachHangActionPerformed

    private void txtTimKiem_KhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiem_KhachHangKeyReleased
        
    }//GEN-LAST:event_txtTimKiem_KhachHangKeyReleased

    private void btnReset_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset_KhachHangActionPerformed
        //        ResKhachHang();
    }//GEN-LAST:event_btnReset_KhachHangActionPerformed

    private void btnXoa_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_KhachHangActionPerformed
        if (validateForm()) {
            if(DialogHelper.confirm(this, "Xác nhận xoá khách hàng?")){
                iKhachHangService.temporaryDeleteKhachHang(setFormKhachHang());
                fillDataTableKhachHang();
            }
        }

    }//GEN-LAST:event_btnXoa_KhachHangActionPerformed

    private void btnSua_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_KhachHangActionPerformed
        if (validateForm()) {
            if(DialogHelper.confirm(this, "Xác nhận sửa khách hàng?")){

                iKhachHangService.updateKhachHang(setFormKhachHang());
                fillDataTableKhachHang();
            }
        }

    }//GEN-LAST:event_btnSua_KhachHangActionPerformed

    private void btnThem_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_KhachHangActionPerformed
        if (validateForm()) {
            if(DialogHelper.confirm(this, "Xác nhận thêm khách hàng?")){
                iKhachHangService.addKhachHang(getFormKhachHang());
                fillDataTableKhachHang();
                DialogHelper.alert(this, "Thêm thành công");
            }
        }
    }//GEN-LAST:event_btnThem_KhachHangActionPerformed

    private void txtDiaChi_KhachHangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChi_KhachHangFocusLost

    }//GEN-LAST:event_txtDiaChi_KhachHangFocusLost

    private void txtTenKhachHang_KhachHangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenKhachHang_KhachHangFocusLost

    }//GEN-LAST:event_txtTenKhachHang_KhachHangFocusLost

    private void txtTenKhachHang_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHang_KhachHangActionPerformed

    }//GEN-LAST:event_txtTenKhachHang_KhachHangActionPerformed

    private void txtTenKhachHang_KhachHangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKhachHang_KhachHangKeyPressed

    }//GEN-LAST:event_txtTenKhachHang_KhachHangKeyPressed

    private void txtTenKhachHang_KhachHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKhachHang_KhachHangKeyTyped

    }//GEN-LAST:event_txtTenKhachHang_KhachHangKeyTyped

    private void txtSDT_KhachHangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDT_KhachHangFocusLost

    }//GEN-LAST:event_txtSDT_KhachHangFocusLost

    private void pnKhachHangComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnKhachHangComponentShown

    }//GEN-LAST:event_pnKhachHangComponentShown

    private void btnThem_KhachHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_KhachHang1ActionPerformed
        // TODO add your handling code here:
        if (ckbTimKiem_KhachHang.isSelected()) {
            String name = txtTimKiem_KhachHang.getText().trim();
            List<KhachHang> customer = iKhachHangService.getDataByName(name);
            modelKhachHang.setRowCount(0);
            for (KhachHang kh : customer) {
                findDataToSQL(kh);
            }
        }
    }//GEN-LAST:event_btnThem_KhachHang1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnReset_KhachHang;
    public static javax.swing.JButton btnSua_KhachHang;
    public static javax.swing.JButton btnThem_KhachHang;
    public static javax.swing.JButton btnThem_KhachHang1;
    public static javax.swing.JButton btnXoa_KhachHang;
    public static javax.swing.JCheckBox ckbTimKiem_KhachHang;
    private javax.swing.JLabel jLabel31;
    public static javax.swing.JLabel jLabel56;
    public static javax.swing.JLabel jLabel85;
    public static javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane24;
    public static javax.swing.JScrollPane jScrollPane25;
    public static javax.swing.JLabel lblDiaChi_KhachHang;
    public static javax.swing.JLabel lblLoiMaKhachHang_KhachHang5;
    public static javax.swing.JLabel lblMaKhachHang_KhachHang;
    public static javax.swing.JLabel lblSDT_KhachHang;
    public static javax.swing.JLabel lblTenKhachHang_KhachHang;
    public static javax.swing.JPanel pnKhachHang;
    public static javax.swing.JTable tblKhachHang_KhachHang;
    public static javax.swing.JTextField txtDiaChi_KhachHang;
    public static javax.swing.JTextPane txtGhiChu_KhachHang;
    public static javax.swing.JTextField txtMaKhachHang_KhachHang;
    public static javax.swing.JTextField txtSDT_KhachHang;
    public static javax.swing.JTextField txtTenKhachHang_KhachHang;
    public static javax.swing.JTextField txtTimKiem_KhachHang;
    // End of variables declaration//GEN-END:variables
}
